app/juegosmundial/urls.py
from django.urls import path
from django.conf.urls import url

from app.juegosmundial.views import juegosmundialbien
from app.juegosmundial.views import equipoidealdescrip
from app.juegosmundial.views import polladescrip
from app.juegosmundial.views import triviainfo
from app.juegosmundial.views import triviajuego
from app.juegosmundial.views import triviafinal


app_name = 'juegosmundial'

urlpatterns = [
    url(r'^juegosbien/', juegosmundialbien, name='juegos_listar'),
    url(r'^equipoideal/', equipoidealdescrip, name='equipoidealinfo'),
    url(r'^polla/',polladescrip , name='pollainfo'),
    url(r'^trivia/info', triviainfo, name='triviainfo'),
    url(r'^trivia/juego',triviajuego , name='triviajuego'),
    url(r'^trivia/final',triviafinal , name='triviafinal'),

]

app/usuario/urls.py
from django.conf.urls import url
from app.usuario.views import RegistroUsuario

app_name = 'usuario'

urlpatterns = [
	url(r'^registrar', RegistroUsuario.as_view(), name='registrar'),

]

rusia2018sw2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import login
from django.conf import settings
from django.conf.urls.static import static
from app.juegosmundial import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('juegosmundial/', include ('app.juegosmundial.urls',namespace = 'juegosmundial')),
    url(r'^usuario/', include('app.usuario.urls', namespace='usuario')),
    url(r'^$', login,{'template_name':'usuario/index.html'},name='login'),
    url(r'^api/trivia', views.triviaList.as_view()),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/juegosmundial/models.py
from django.db import models

class Pregunta(models.Model):
    descpregunta =  models.CharField(max_length=400)
    
    def __str__ (self):
        return self.descpregunta


class Respuesta(models.Model):
    descrespuesta =  models.CharField(max_length=400)
    def __str__ (self):
        return self.descrespuesta

class PrexRes(models.Model):
    idpregunta =  models.ForeignKey(Pregunta ,on_delete=models.CASCADE,)
    idrespuesta =  models.ForeignKey(Respuesta ,on_delete=models.CASCADE)
    res_val = models.BooleanField(default=False)

    def __str__ (self):
        return str(self.idpregunta) + " / " + str(self.idrespuesta) + " / " + str(self.res_val)

app/usuario/models.py
from django.db import models

# Create your models here.

app/juegosmundial/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import PrexRes
from .models import Pregunta
from .models import Respuesta
from .serializers import PreguntaSerializer
from .serializers import RespuestaSerializer
from .serializers import PrexResSerializer

# Create your views here.

def juegosmundialbien(request):
	return render(request, 'usuario/bienvenido.html')

def equipoidealdescrip(request):
	return render(request, 'juegos/DescripEquipoIdeal.html')	

def polladescrip(request):
	return render(request, 'juegos/DescripPolla.html')

#TRIVIA
def triviainfo(request):
	return render(request, 'juegos/trivia/descripcion.html')

def triviajuego(request):
	return render(request, 'juegos/trivia/juego.html')

def triviafinal(request):
	return render(request, 'juegos/trivia/final.html')



class triviaList(APIView):
	def get(self,request):
		preguntag = Pregunta.objects.all()
		respuestag = Respuesta.objects.all()
		prexres = PrexRes.objects.all()

		serializerPregunta = PreguntaSerializer(preguntag , many=True)
		serializerRespuesta = RespuestaSerializer(respuestag , many=True)
		serializerPreXRes = PrexResSerializer(prexres , many=True)

		return Response(serializerPreXRes.data + serializerPregunta.data + serializerRespuesta.data)

	def post(self):
		pass

app/usuario/views.py
from django.shortcuts import render

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy

from app.usuario.form import RegistroForm

# Create your views here.

class RegistroUsuario(CreateView):
	model = User
	template_name = "usuario/registrar.html"
	form_class = RegistroForm
	success_url = reverse_lazy('juegosmundial:juegos_listar')

templates/base/base.html
{% load staticfiles %}
{% csrf_token %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/prueba.css' %}">
	<!--Agregando-->
	<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
	

{% block link%}  {%endblock %}

	<title>{% block title%} Rusia2018SW2 {%endblock %}</title>
 <!--Agregamdo -->
 <!-- Font Awesome -->


  <style>
{% block style%}  {%endblock %}
       input {
       	 width: 40%;
       }

      .intro-2 {
          background: url("https://pbs.twimg.com/profile_background_images/626100471086850049/8WBVDw0m.jpg")no-repeat center center;
          background-size: cover;
      }

      
  </style>

</head>
<body class="container intro-2">

	{% block header%}

	{%endblock %}

	{% block content %}

	<h4>Este es el contenido del archivo base</h4>

	{% endblock %}


	{% block footer%}


	{%endblock %}

	<!--Agregando-->
 

	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block script%}  {%endblock %}
</body>
</html>

templates/juegos/DescripEquipoIdeal.html
{% extends 'base/base.html' %}
 
{% block link%} 

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css" type="text/css"> </head>

 {%endblock %}

 

{% block content %}
{% csrf_token %}
<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header text-uppercase text-center bg-dark text-light"> Descripción de Equipo Ideal</div>
            <div class="card-body">
              <h4>El equipo ideal es un juego que te permite armar tu equipo con los jugadores que conformarían el once ideal de todo el mundo.</h4>
              <h4>Intrucciones:</h4>
              <h4>1. Elige la formación.</h4>
              <h4>2. Selecciona la poscición del jugador.</h4>
              <h4>3. Selecciona el país de tu jugadror.</h4>
              <h4>4. Selecciona tu jugador.</h4>
              <h4>5. Guarda tu equipo ideal!</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <a href="#" class="btn btn-primary btn-lg">Comenzar</a>
            <!-- <a href="" class="btn btn-primary btn-lg" href="" target="" data-toggle="">Comenzar</a>  -->

        </div>
      </div>
    </div>
  </div>

  {% endblock %}

templates/juegos/DescripPolla.html
{% extends 'base/base.html' %}
 
{% block link%} 

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css" type="text/css"> </head>

 {%endblock %}

 

{% block content %}
{% csrf_token %}


  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header text-uppercase text-center bg-dark text-light"> Descripción de Polla</div>
            <div class="card-body">
              <h4>La polla es un juego que te permite apostar a tu equipo ganador o apostar por un empate.</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <a href="#" class="btn btn-primary btn-lg">Comenzar</a>
            <!-- <a href="" class="btn btn-primary btn-lg" href="" target="" data-toggle="">Comenzar</a>  -->

        </div>
      </div>
    </div>
  </div>





{% endblock %}

templates/juegos/equipoideal/descripcion.html
{% extends 'base/base.html' %}
 
{% block link%} 

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css" type="text/css"> </head>

 {%endblock %}

 

{% block content %}
{% csrf_token %}
<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header text-uppercase text-center bg-dark text-light"> Descripción de Equipo Ideal</div>
            <div class="card-body">
              <h4>El equipo ideal es un juego que te permite armar tu equipo con los jugadores que conformarían el once ideal de todo el mundo.</h4>
              <h4>Intrucciones:</h4>
              <h4>1. Elige la formación.</h4>
              <h4>2. Selecciona la poscición del jugador.</h4>
              <h4>3. Selecciona el país de tu jugadror.</h4>
              <h4>4. Selecciona tu jugador.</h4>
              <h4>5. Guarda tu equipo ideal!</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <a href="#" class="btn btn-primary btn-lg">Comenzar</a>
            <!-- <a href="" class="btn btn-primary btn-lg" href="" target="" data-toggle="">Comenzar</a>  -->

        </div>
      </div>
    </div>
  </div>

  {% endblock %}

templates/juegos/polla/descripcion.html
{% extends 'base/base.html' %}
 
{% block link%} 

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css" type="text/css"> </head>

 {%endblock %}

 

{% block content %}
{% csrf_token %}


  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header text-uppercase text-center bg-dark text-light"> Descripción de Polla</div>
            <div class="card-body">
              <h4>La polla es un juego que te permite apostar a tu equipo ganador o apostar por un empate.</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <a href="#" class="btn btn-primary btn-lg">Comenzar</a>
            <!-- <a href="" class="btn btn-primary btn-lg" href="" target="" data-toggle="">Comenzar</a>  -->

        </div>
      </div>
    </div>
  </div>





{% endblock %}

templates/juegos/trivia/descripcion.html
{% extends 'base/base.html' %} {% load staticfiles %} {% block link%}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="https://v40.pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css" type="text/css"> </head>

{%endblock %} {% block content %} {% csrf_token %}


<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header text-uppercase text-center bg-dark text-light"> Descripción de TRIVIA</div>
          <div class="card-body">
            <h4>La Trivia es un juego de habilidad donde el jugador debe contestar preguntas sobre el mundial de fútbol. Cada
              pregunta bien contestada acumula puntaje, con distintas opciones para elegir como respuesta y debe hacerlo
              dentro de un determinado tiempo.
            </h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <a id="jugar" href="{% url 'juegosmundial:triviajuego' %}" class="invisible btn btn-primary btn-lg">Comenzar</a>
        <!-- <a href="Trivia/quiz.html" class="btn btn-primary btn-lg" href="" target="" data-toggle="">Comenzar</a>  -->

      </div>
    </div>
  </div>
</div>
{% endblock %} {% block script%}
<script src="https://cdn.jsdelivr.net/npm/alasql@0.4"></script>
<script src="{% static 'js/trivia/info.js' %}"></script> {%endblock %}

templates/juegos/trivia/final.html
{% extends 'base/base.html' %} {% load staticfiles %} {% block link%}


<link rel="stylesheet" href="{% static 'css/triviajuegocss.css' %}">
<link rel="stylesheet" href="{% static 'css/temporizador.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> {%endblock %} {% block content %} {% csrf_token %}
<br>
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="w3-container" >
            <div class="w3-card-12 w3-blue-grey">
                <div class="w3-container w3-center">
                    <h1>Puntos</h1>
                    <div class="w3-section">
                        <h3 id="puntos">...</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-sm-12" style="text-align: center; margin-top: 50px;">
        <a href="{% url 'juegosmundial:triviainfo' %}" class="btn btn-primary btn-lg">Regresar</a>
    </div>
</div>
<br>

{% endblock %} {% block script%}


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
    crossorigin="anonymous"></script>
<script type="text/javascript" async="" src="https://ssl.google-analytics.com/ga.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/trivia/final.js' %}"></script> {%endblock %}

templates/juegos/trivia/juego.html
{% extends 'base/base.html' %} {% load staticfiles %} {% block link%}


<link rel="stylesheet" href="{% static 'css/triviajuegocss.css' %}">
<link rel="stylesheet" href="{% static 'css/temporizador.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> {%endblock %} {% block content %} {% csrf_token %}

<div class="container">
    <h2 style="text-align: center" class="well">Progreso de preguntas completadas:</h2>
    <div class="progress">
        <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0"
            aria-valuemax="100" style="width:0%" id="progresopreg">
            0%
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="w3-container" style="margin-left: 45%">
            <div class="w3-card-4 w3-blue-grey" style="width:50%">
                <div class="w3-container w3-center">
                    <h1>Puntos</h1>
                    <div class="w3-section">
                        <h3 id="puntos">0 pts</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="w3-container">


            <div class="progresss blue">
                <span class="progress-left">
                    <span id="aux1" class="pg progress-bar"></span>
                </span>
                <span class="progress-right">
                    <span id="aux2" class="pg progress-bar"></span>
                </span>
                <div id="temporizador" class="progress-value">0</div>
            </div>

        </div>
    </div>

</div>
<br>

<div class="container-fluid bg-info">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <!--Aqui van la preguntas-->
                <h3 id="pregunta">
                    <!--<span class="label label-warning" id="qid">1</span> 
                    ¿Qué director técnico ha logrado alzarse con la Copa del Mundo en más de una ocasión?-->
                </h3>
            </div>
            <div class="modal-body">
                <div class="col-xs-3 col-xs-offset-5">
                    <div id="loadbar" style="display: none;">
                        <div class="blockG" id="rotateG_01"></div>
                        <div class="blockG" id="rotateG_02"></div>
                        <div class="blockG" id="rotateG_03"></div>
                        <div class="blockG" id="rotateG_04"></div>
                        <div class="blockG" id="rotateG_05"></div>
                        <div class="blockG" id="rotateG_06"></div>
                        <div class="blockG" id="rotateG_07"></div>
                        <div class="blockG" id="rotateG_08"></div>
                    </div>
                </div>

                <div class="quiz" id="quiz" data-toggle="buttons">
                    <!--Aqui van las respuestas-->
                    <label id="p1" class="foc element-animation1 btn btn-lg btn-primary btn-block">
                        <!--<span class="btn-label">
                            <i class="glyphicon glyphicon-chevron-right">

                            </i>
                        </span>
                        <input type="radio" name="q_answer" value="0">Luiz Felipe Scolari--></label>

                    <label id="p2" class="foc element-animation2 btn btn-lg btn-primary btn-block">
                        <!--<span class="btn-label">
                            <i class="glyphicon glyphicon-chevron-right">

                            </i>
                        </span>
                        <input type="radio" name="q_answer" value="1">Vittorio Pozzooooooooo--></label>

                    <label id="p3" class="foc element-animation3 btn btn-lg btn-primary btn-block">
                        <!--<span class="btn-label">
                            <i class="glyphicon glyphicon-chevron-right">

                            </i>
                        </span>
                        <input type="radio" name="q_answer" value="2">Marcello Lippi--></label>

                    <label id="p4" class="foc element-animation4 btn btn-lg btn-primary btn-block">
                        <!--<span class="btn-label">
                            <i class="glyphicon glyphicon-chevron-right">

                            </i>
                        </span>
                        <input type="radio" name="q_answer" value="3">Franz Beckenbauer--></label>

                </div>
            </div>
            <div class="modal-footer text-muted">
                <span id="answer"></span>
            </div>
        </div>
    </div>
</div>



{% endblock %} {% block script%}


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
    crossorigin="anonymous"></script>
<script type="text/javascript" async="" src="https://ssl.google-analytics.com/ga.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="{% static 'js/trivia/juego.js' %}"></script> {%endblock %}

templates/usuario/bienvenido.html
{% extends 'base/base.html' %}
{% block link%} 


	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
 {%endblock %}

 {% block style%}  

 
{%endblock %}



{% block content %}
  {% csrf_token %}
 

<br><br><br><br><br><br>
<div class="row">
  <div class="col-lg-4">



<div class="w3-container">

  <div class="w3-card-4 w3-blue-grey" style="width:100%">

    <div class="w3-container w3-center">
      <br>
      <img src="http://www.unica.edu.pe/publicacion/App/trivia/img/trivia.png" alt="Avatar" style="width:100%">
	<br>
      <div class="w3-section">
        <a href="{% url 'juegosmundial:triviainfo' %}" class="w3-button w3-blue">Trivia</a>
	<br>
      </div>
    </div>

  </div>
</div>

  </div>
  
  <div class="col-lg-4">

<div class="w3-container">

  <div class="w3-card-4 w3-blue-grey" style="width:100%">

    <div class="w3-container w3-center">
      <br>
      <img src="https://comutricolor.com/wp-content/uploads/2016/03/Once-Ideal-Eliminatoria-Rusia-2018.png" alt="Avatar" style="width:80%">

      <div class="w3-section">
        <a href="{% url 'juegosmundial:equipoidealinfo' %}" class="w3-button w3-blue">Once Ideal</a>

      </div>
    </div>

  </div>
</div>

  </div>
  
  <div class="col-lg-4">



<div class="w3-container">

  <div class="w3-card-4 w3-blue-grey" style="width:90%">

    <div class="w3-container w3-center">
      <br>
      <img src="https://www.trebol-apuestas.com/wp-content/uploads/2017/11/El-f%C3%BAtbol-puede-existir-sin-las-apuestas.jpg" alt="Avatar" style="width:70%">

      <div class="w3-section">
        <a href="{% url 'juegosmundial:pollainfo' %}" class="w3-button w3-blue">Polla</a>

      </div>
    </div>

  </div>
</div>




  </div>

</div>
 
 
  {% endblock %}
  {% block script%}  
 {%endblock %}

templates/usuario/index.html
{% extends 'base/base.html' %}

{% block content %}
{% csrf_token %}

<div align="center" style="color:white"> 

<h1 style="font-family:Indie Flower ;margin-top: 2cm ; font-size: 100px">APUESTAPE</h2>

<form method="post" style="margin-top: 2cm; font-size: 30px" >
  {% csrf_token %}


  <div class="form-group">
    <label for="text">Usuario</label>
    <input  style="width: 40%" type="text" class="form-control" placeholder="Username" name="username">
  </div>
  <div class="form-group" >
    <label for="pwd">Password:</label>
    <input style="width: 40%"  type="password" class="form-control" placeholder="Password" name="password">
  </div>
  <div class="form-group" >
     <button  type="submit" class="btn btn-info">Ingresar</button>
  </div>

</form>


  <div class="form-group" >
     <a  class= "btn btn-info" href="{% url 'usuario:registrar' %}">Registrarse </a>
  </div>

</div>  
  {% endblock %}

templates/usuario/registrar.html
{% extends 'base/base.html' %}

{% block content %}


<div align="center" style="color:white"> 

<h2 style="font-family:Indie Flower ;margin-top: 1cm ; font-size: 100px">APUESTAPE</h2>



<form method="post" style="margin-top: 1cm; font-size: 20px">
  {% csrf_token %}
  

  <div class="form-group">
    <label for="text">Nombre:</label>
    <input type="text" style="width: 30%" class="form-control" name="first_name" placeholder="Nombre">
  </div>
  <div class="form-group">
    <label for="text">Apelido:</label>
    <input type="text" style="width: 30%" class="form-control" name="last_name" placeholder="Apelido">
  </div>
  <div class="form-group">
    <label for="text">Usuario:</label>
    <input type="text" style="width: 30%" class="form-control" name="username" placeholder="Usuario">
  </div>
  <div class="form-group">
    <label for="email">Email:</label>
    <input type="email" style="width: 30%" class="form-control" name="email" placeholder="@Email">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" style="width: 30%" class="form-control" name="password1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="pwd">Repetir Password:</label>
    <input type="password" style="width: 30%" class="form-control" name="password2" placeholder="PasswordS">
  </div>
  <div class="form-group">
     <button type="submit" style="width: 30%" class="btn btn-primary">Guardar</button>
  </div>

</form>

</div>
  {% endblock %}